### ISSUE TITLE
What is the effect of Cache?

### ISSUE THREAD

**Issue by raywzy** [hjwdzh/AdversarialTexture#2]
Very impressive work! While checking the dataset file, I found you utilize the cache to ensure no repeat calculation for each source image. But it will lead to one-to-one matching during training, rather than selecting the target view randomly. Is it right?

**Comment by hjwdzh** [comment]
You made a very good point that I probably ignore it myself!

The cache is only aiming for acceleration, but I did not find that it leads to one-to-one matching -- It is a bug when I refactor my code for release.

You are free to turn it off, and it probably gives similar or even better result.

**Comment by raywzy** [comment]
> You made a very good point that I probably ignore it myself!
> 
> The cache is only aiming for acceleration, but I did not find that it leads to one-to-one matching -- It is a bug when I refactor my code for release.
> 
> You are free to turn it off, and it probably gives similar or even better result.

Thanks for your reply :)
