### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by raywzy** [hjwdzh/AdversarialTexture#3]
Dear Jingwei, I have other two questions about the code

- In Line128 of dataset.py, why 1-uv?

- In Line 146 of model.py, why discrim_loss is set to 0 when it is greater than gen_loss_GAN?

**Comment by hjwdzh** [comment]
1. it is all about difference between uv space and image space -- in uv 0 is bottom and 1 is top, while in image space 0 is top and 1 is bottom.

2. I find discriminator is easy to overwhelm. Therefore when discriminator dominates, I only optimize the texture so that they can be rebalanced.

**Comment by raywzy** [comment]
> 1. it is all about difference between uv space and image space -- in uv 0 is bottom and 1 is top, while in image space 0 is top and 1 is bottom.
> 2. I find discriminator is easy to overwhelm. Therefore when discriminator dominates, I only optimize the texture so that they can be rebalanced.

Thanks for your reply! BTW, do you plan to release the codes of 3D data generation part of supplementary? I am not very familiar of this area, but I really want to try how large geometry errors your method could handle :) Or it will be better that you could give me some related work.

**Comment by hjwdzh** [comment]
Please see data/preprocessing. There are rendering code given the camera poses. I used very similar code to create synthetic examples with different camera/geometry errors.

**Comment by raywzy** [comment]
> Please see data/preprocessing. There are rendering code given the camera poses. I used very similar code to create synthetic examples with different camera/geometry errors.

Thank you very much!
