### ISSUE TITLE
About custom dataset

### ISSUE THREAD

**Issue by zhongtao93** [hjwdzh/AdversarialTexture#4]
Hi, thank you for sharing source code, it's a fancy work!

I have a question about using custom dasaset. Since I have some RGBD dataset, I composed it to .sens file like BundleFusion (e.g. apt0.sens). But it couldn't work well using render_scan.py. 

Any suggestion or is  there a detail about how your .sens file composed?

Thank you~

**Comment by hjwdzh** [comment]
https://github.com/ScanNet/ScanNet/tree/master/SensReader/c%2B%2B

This tool will unpack the sens files into camera poses, intrinsic, depth and rgb. These are sufficient for rendering. Maybe you need to slightly modify the code/file-naming to use render_scan.py, but it should not be too hard.
